sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u failender -p $DOCKER_PASS
      - docker build -t failender/dgo-proxy:$TRAVIS_BRANCH .
      - docker push failender/dgo-proxy

